= Create a New Activity
:toc:
:icons: font
:experimental:
:source-highlighter: highlight.js

To create a new activity, follow these steps:

. In Uptempo, click Activities in the navigation sidebar.
. In the Activities section, click Create Activity. The button is available on both the Timeline and Summary views:
. On the Type page:
.. Use the Activity type list to select the type of activity you want to create from the available options.
.. Use the Parent list to select the activity under which you want to create this new activity in the hierarchy.
.. Click Next.
. On the Details page:
.. Enter a name for your new activity into the Name field.
.. Optional: To set the date range when this activity will be in-market, use the In-market Dates fields to choose a start and end date.
.. Depending on the activity type you selected, additional attribute fields may be displayed.
. On the Budget page:
.. Optional: To enter a cost estimate for this activity, use the Estimated Costs field.
.. Optional: To connect this activity to an investment, click Add funding source.
.. Click Next.
. On the Impact page:
.. Optional: If the parent activity you selected on the Type page allows child activities with performance data, you can configure the performance data here.
.. If no additional steps are displayed after the Impact step, skip to step 8.
.. If a Workflow step is available, click Next.
. On the Workflow step:
.. Optional: If the activity is linked with a workflow, decide when the workflow will be started.
. Click Submit to finish creating the activity.


=== Connecting Activities to Financial Items

You can connect activities at various levels to one or multiple investments. To connect activities to investments, follow these steps:

. On the activity where you want to connect investments, open the Budget page:
.. While creating a new activity, go to the Budget page in the Create Activity panel.
.. For an existing activity, go to the Activities section and click on the activity in the hierarchy to open its Details panel, then click the Budget tab.
. Click Add Funding Source.
. Select the budget you want to use from the Select Budget lists.
. In the Investment Item list, find the investment you want to connect. Click an investment item's Link button to connect it to the activity.
. Click on a subsection to expand it and see the details of the connected investment.
. Optional: To connect additional investments to the activity, click Add funding source again and repeat steps 3 and 4.
. Finish up:
.. If you're creating a new activity, finish creating the activity and click Submit to apply your changes.
.. If you're editing an existing activity, close the activity's Details tab to apply your changes.


=== Configuring Planned Impact

If the activity is a point where plan performance data is to be captured:

. Add the number of requests the activity is expected to generate.
. In case you want to edit the distribution:
.. Select Monthly or Quarterly (distribution) in the Distribute Results dropdown.
.. Click Edit distribution.
.. Edit the number of inquiries per time range as desired.
